services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "3000:8080"
    volumes:
      - .:/usr/src/app
    command: go run ./cmd/server/main.go -b 0.0.0.0
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "3001:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/insert.sql:/docker-entrypoint-initdb.d/2-schema.sql

volumes:
  postgres-db:
